At statement after exception
At statement after 1st try-except
Finally!
Caught my own memory access violation, ignoring it!
Exception address and target match!
Register match!
After exception handler
#if +PROGRAM_SHEPHERDING : +-security --executable_heap +-no_executable_if_hook --executable_if_text --executable_if_x --X
# if : --detect_mode
#  if : +-throw_exception
#   SEC_VIO_EXCEPTION
//  the exception handler is also bad (on same page as faulting function)
#   if : --throw_exception_max 1
#    SEC_VIO_EXCEPTION
#    SEC_VIO_EXCEPTION
#    SEC_VIO_EXCEPTION
#    SEC_VIO_EXCEPTION
#    SEC_VIO_EXCEPTION
#    SEC_VIO_EXCEPTION
#    SEC_VIO_EXCEPTION
#    SEC_VIO_EXCEPTION
#    SEC_VIO_EXCEPTION
#   endif
#  endif
#  if : +-kill_thread
#    SEC_VIO_THREAD
#  else  
#    SEC_VIO_STOP
#  endif
#  if : --internal_detach_mask
#   STOP
#  endif
# else
#  SEC_VIO_CONT
# endif
#endif
At statement after exception
At statement after 1st try-except
Finally!
Caught my own memory access violation, ignoring it!
Exception address and target match!
Register match!
After exception handler
At statement after exception
At statement after 1st try-except
Finally!
Caught my own memory access violation, ignoring it!
Exception address and target match!
Register match!
After exception handler
